# Generated by Django 2.2.1 on 2019-05-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorID', models.CharField(max_length=100)),
                ('objectID', models.CharField(max_length=100)),
                ('objectType', models.CharField(max_length=100)),
                ('pfand', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('prevhash', models.CharField(max_length=100)),
            ],
        ),
    ]
