# Generated by Django 2.2.1 on 2019-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_block_sighash'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='prevID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
